### ISSUE TITLE
Please provide video walkthrough

### ISSUE THREAD

**Issue by thedarkjester** [kdluukdluu/blockchain-developer-bootcamp-final-project#1]
Hi,

I see your video walkthrough and ethereum address is missing from the submission.

Please provide at least the video.

Kindly add system and pre-requisites for installing (e.g. python/pip)

**Comment by kdluukdluu** [comment]
Hi,

I have already provided the screen shots walkthrough under file name ProjectOneScreenShots.docx.  Let me know if this is NOT sufficient and I still have to make a video.

I have also provided the deployed_address,txt file so I'm not sure why you said that the address is missing from the submission.

I have Python 3.9.2 installed on my Windows laptop.  You can download this specific version and install on your machine from https://www.python.org/downloads/ 

Thanks!

**Comment by thedarkjester** [comment]
Hi,

I didn't see any reference to the doc. Will have a look.

The ethereum address I mean is your personal address where, if we send NFT certifications will go.

**Comment by kdluukdluu** [comment]
Hi,

I did not provide my ethereum address since I thought it was an optional.  Anyway, it is at 0x268c93a5e332Fe54d909B351BE7AA391AacaB094

Thanks!
